### ISSUE TITLE
etcd-operator should allow setting of tolerations on etcd pods

### ISSUE THREAD

**Issue by aaronlevy** [coreos/etcd-operator#968] opened 2017-04-19 17:27 UTC
In k8s v1.6 we can now set taints/tolerations - which will allow for "dedicated" nodes (e.g. "dedicated etcd nodes" or "dedicated master nodes".)

etcd-operator should allow setting tolerations on the etcd pods that get launched to support these deployment methods.

It seems like we could bump to client-go v3 (which is still in beta, but based on comment in a similar version bump for flannel I trust this to be stable: https://github.com/coreos/flannel/pull/677#issuecomment-294206139)

The other option might be to just implement a custom stub type of tolerations such that they get serialized in the pod spec - but we don't need to bump the client-go version.

**Comment by aaronlevy** [comment] 2017-04-19 17:28
xref: https://github.com/kubernetes-incubator/bootkube/issues/452

**Comment by aaronlevy** [comment] 2017-04-19 17:38
Actually - based on this issue (using patch() rather than update()): https://github.com/coreos/etcd-operator/issues/966 -- really would need to bump to client-go v3.0.0 -- otherwise tolerations will be stripped when etcd pod is updated.

**Comment by xiang90** [comment] 2017-04-19 19:06
@aaronlevy We discussed this issue a while ago. We should taint master nodes for small clusters and taint etcd nodes for large clusters.

from etcd operator point of view, we care about the latter more, but it is a generic setting user can set anyway. The feature is tracked here: https://github.com/coreos/etcd-operator/blob/master/doc/best_practices.md#assign-to-dedicated-node-work-in-progress.

Now, taint is a beta feature for 1.6. We need to:

1. bump client-go to 3.0 which is not that easy due to the api breakage and potential regression: see https://github.com/coreos/etcd-operator/pull/967

2. add taint into pod policy spec

3. implement taint and test it

4. release a new version of etcd operator

We do not really have a timeline right now. If this is something urgent, it can be expedited though.

**Comment by aaronlevy** [comment] 2017-04-19 22:59
@xiang90 This would be a priority change as it blocks the ability for implemented "dedicated" master nodes.

**Comment by xiang90** [comment] 2017-04-20 21:22
fixed by #969

**Closed by xiang90** 2017-04-20 21:22 UTC
