### ISSUE TITLE
Etcd Operator ignores the custom storageClass

### ISSUE THREAD

**Issue by dmyerscough** [coreos/etcd-operator#1389] opened 2017-09-10 06:26 UTC
I trying to spin up the Etcd Operator with backup on minikube. However, every time I specified a custom storage type the operator kept trying to use "etcd-backup-gce-pd"

```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster-with-backup"
spec:
  size: 3
  version: "3.1.8"
  backup:
    # short snapshot interval for testing, do not use this in production!
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "PersistentVolume"
    pv:
      volumeSizeInMB: 512
      storageClass: standard
```

```
Sep 10 06:22:30 minikube localkube[3755]: E0910 06:22:30.745826    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
```

**Comment by xiang90** [comment] 2017-09-10 06:37
@dmyerscough what is the version of etcd operator?

**Comment by dmyerscough** [comment] 2017-09-11 03:04
Sorry about that; the version was `v0.5.1`

**Comment by xiang90** [comment] 2017-09-11 03:06
@fanminshi @hongchaodeng can you take a look? i feel this is a bug.

**Comment by hongchaodeng** [comment] 2017-09-11 15:54
Canot reproduced.

**Comment by hongchaodeng** [comment] 2017-09-11 16:05
@dmyerscough 
Please provide more details how you can reproduce the problem

**Comment by dmyerscough** [comment] 2017-09-11 16:54
I just tried the following:-

```
localhost ~$ kubectl get nodes
NAME       STATUS    AGE       VERSION
minikube   Ready     2d        v1.7.5

localhost ~$ kubectl create -f https://raw.githubusercontent.com/coreos/etcd-operator/v0.5.1/example/deployment.yaml
deployment "etcd-operator" created
localhost ~$ kubectl get storageclass
NAME                 TYPE
standard (default)   k8s.io/minikube-hostpath   

localhost ~$ cat test.yaml 
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster-with-backup"
spec:
  size: 3
  version: "3.1.8"
  backup:
    # short snapshot interval for testing, do not use this in production!
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "PersistentVolume"
    pv:
      volumeSizeInMB: 512
      #storageClass: standard
```

Noticed I left the `storageClass` commented out (Default is GCE). I did the apply against minikube which is expected to fail because there is no GCE storage. However, if you `kubectl delete -f test.yaml` you will notice that it doesn't delete the GCE `storageClass` that the etcd operator created.

When I modified the `storageClass` to `standard` the etcd Operator still does not seem to create the instances... Maybe, I am dealing with a borked minikube or it has something to do with the GCE `storageClass` that gets created.

**Comment by fanminshi** [comment] 2017-09-11 16:58
taking a look as well.

**Comment by hongchaodeng** [comment] 2017-09-11 18:12
@dmyerscough 

Can you provide etcd-operator logs?

> localhost ~$ kubectl create -f https://raw.githubusercontent.com/coreos/etcd-operator/v0.5.1/example/deployment.yaml

If you are using minikube, please set flag

```
etcd-operator --pv-provisioner=none
```

By default, it's "kubernetes.io/gce-pd". We will deprecate this flag later and only use cluster spec only.

**Comment by hongchaodeng** [comment] 2017-09-11 18:19
> Noticed I left the storageClass commented out (Default is GCE). I did the apply against minikube which is expected to fail because there is no GCE storage.

"apply" doesn't work now. Please set the "storageClass" field at creation.

**Comment by xiang90** [comment] 2017-09-19 17:32
@dmyerscough kindly ping.

**Comment by dmyerscough** [comment] 2017-09-19 18:00
@xiang90 I will take a look at this shortly, Ill update by EOD.

**Comment by dmyerscough** [comment] 2017-09-21 05:02
@hongchaodeng the logs are not available because the pods are never started.

How do you set

```
etcd-operator --pv-provisioner=none
```

Minikube logs:-

```
Sep 21 05:00:24 minikube localkube[3755]: E0921 05:00:24.663084    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
Sep 21 05:00:32 minikube localkube[3755]: W0921 05:00:32.088673    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Sep 21 05:00:39 minikube localkube[3755]: E0921 05:00:39.663435    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
Sep 21 05:00:42 minikube localkube[3755]: W0921 05:00:42.109653    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Sep 21 05:00:52 minikube localkube[3755]: W0921 05:00:52.132018    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Sep 21 05:00:54 minikube localkube[3755]: E0921 05:00:54.663545    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
Sep 21 05:01:02 minikube localkube[3755]: W0921 05:01:02.156616    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Sep 21 05:01:09 minikube localkube[3755]: E0921 05:01:09.663636    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
Sep 21 05:01:12 minikube localkube[3755]: W0921 05:01:12.179042    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Sep 21 05:01:22 minikube localkube[3755]: W0921 05:01:22.201576    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
Sep 21 05:01:24 minikube localkube[3755]: E0921 05:01:24.663765    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
Sep 21 05:01:32 minikube localkube[3755]: W0921 05:01:32.223125    3755 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
```

**Comment by dmyerscough** [comment] 2017-09-21 05:22
Ok, I found the issue. When issuing a `kubectl delete -f ....` the PVC was not deleted and the `kubectl create -f ....` did not throw any errors.

**Comment by xiang90** [comment] 2017-09-21 05:55
@dmyerscough 

Do you think we should improve any documentation around this issue?

**Comment by dmyerscough** [comment] 2017-09-21 06:01
@xiang90 actually that's a good point. We should state that when you `delete` the backup pod; ensure the PVC is removed too.

This would be good since GCE storage is used by default if no `storageclass` is specified. However, the operator should just use the default `storageclass` that is defined on the cluster.

**Comment by xiang90** [comment] 2017-09-21 06:35
@dmyerscough I reopened this and marked it as a documentation issue. We will address it.

**Comment by hongchaodeng** [comment] 2017-09-21 15:01
Can you point out where the docs need to b explicitly mention?
Where do you read the docs from?

**Comment by hongchaodeng** [comment] 2017-10-19 21:00
Clear since unclear what to act on.
Deleting PVC is mentioned in https://github.com/coreos/etcd-operator#disaster-recovery .

**Closed by hongchaodeng** 2017-10-19 21:00 UTC
Labels: kind/documentation

**Comment by dmyerscough** [comment] 2017-10-19 21:06
Does the Operator still use GCE as the default storage engine for backups?

**Comment by hongchaodeng** [comment] 2017-10-19 21:10
@dmyerscough 
We are decoupling the backup operation logic from etcd operator.
In the future, the default storage for backup will be S3. But that's very decoupled will be less confusing.

**Comment by dmyerscough** [comment] 2017-10-19 21:41
Why is it still being tied to a specific backend, is it not possible to have this completely abstracted or force the user to actually specify it without trying to guess?

**Comment by hongchaodeng** [comment] 2017-10-19 21:48
>  is it not possible to have this completely abstracted or force the user to actually specify it without trying to guess?

Yeah. That's the plan. I will work out some detailed specification and publish in issue.
