### ISSUE TITLE
Questions about setting up backups

### ISSUE THREAD

**Issue by balboah** [coreos/etcd-operator#1787] opened 2017-12-18 14:30 UTC
After playing a bit with the operator and sometimes getting stuck with a bad cluster state. I decided to read the documentation and [examples](backups) about how to setup backups as I don't manually want to delete and re-create `EtcdCluster` if it would be a real crash. However I'm left with a couple of questions about the `EtcdBackup` definition in v0.7.2:

1. Do you need to specify `EtcdEndpoints`? I'm expecting to set the cluster name and to have the endpoints discovered for me, as thats the input for the `EtcdCluster` definition.

2. The [example](backups) ends with "then check the status to be succeeded", do you need to create the `EtcdBackup` entry at the point in time that you want to create the backup for? Are there no automatic backup scheduled? I would expect it to act like a cron job daemon that sits in the background and does these continuous backups.

3. Is restoring done by manually submitting an `EtcdRestore`? Should this not be handled by the operator whenever it fails to recover a cluster with broken pods?

4. Thanks for the great work and sorry for any missinterpretations of the examples in advance :) 

[backups]: https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/backup-operator.md

**Comment by raoofm** [comment] 2017-12-18 17:30
@balboah Great, you penned down some question I had too. I know that for point 1, they removed EtcdCluster and added EtcdEndpoints so that backup-operator could be used for etcd clusters which were not set up by etcd-operator. But I strongly believe that this should definitely have EtcdCluster feature as that is the primary usecase which most people would use.

 I would like to add one more to the list

5. As etcd-operator is supposed to run on kubernetes, Doesn't it make sense to give the ability for the backup and restore to work with kube2iam assume role annotation rather than aws keys.

**Comment by balboah** [comment] 2017-12-19 08:38
@raoofm great to know I'm not the only dummy here ;) Sounds like a good addition although I'm not using AWS

**Comment by hongchaodeng** [comment] 2017-12-19 19:17
Hi @balboah @raoofm 
Thanks for raising the question.

> Do you need to specify EtcdEndpoints

We want backup operator to also support etcd cluster outside k8s.
I understand etcd operator specific clusterName is convenient. We are busy right now and can only revisit this again in Feb 2018. Mind submit an issue?

> The example ends with "then check the status to be succeeded", do you need to create the EtcdBackup entry at the point in time that you want to create the backup for? Are there no automatic backup scheduled? I would expect it to act like a cron job daemon that sits in the background and does these continuous backups.

Yes. We use k8s CronJob and/or jenkins to automate that.

> Is restoring done by manually submitting an EtcdRestore? Should this not be handled by the operator whenever it fails to recover a cluster with broken pods?

Restore operator will clean up those broken pods when restoring an etcd cluster.

> As etcd-operator is supposed to run on kubernetes, Doesn't it make sense to give the ability for the backup and restore to work with kube2iam assume role annotation rather than aws keys.

In CoreOS, we have teams concerned about security of kube2iam. Currently we encourage to use temporal STS tokens and write that down into a secret.

**Comment by raoofm** [comment] 2017-12-20 22:38
>Is restoring done by manually submitting an EtcdRestore? Should this not be handled by the operator whenever it fails to recover a cluster with broken pods?

>Restore operator will clean up those broken pods when restoring an etcd cluster.

@hongchaodeng I think what @balboah was trying to ask is - Does not the etcd-operator itself figure out the complete cluster failure and trigger the restore-operator? Why is there a manual step to deploy restore-operator which could add up the delays.

>Yes. We use k8s CronJob and/or jenkins to automate that.

Cron Job is fine too, but it seems more natural for the backup-operator to have that as the native functionality. If not a sample cron in the examples will help users to be clear that those backups are one time.

**Comment by hongchaodeng** [comment] 2017-12-21 17:47
> Does not the etcd-operator itself figure out the complete cluster failure and trigger the restore-operator...
>  but it seems more natural for the backup-operator to have that as the native functionality.

It's paramount to keep etcd operator simple and make it stable for open source purpose.
Complexity around automatic trigger for backup/restore is up to business logic.

> If not a sample cron in the examples will help users to be clear that those backups are one time.

Will work on that. It sounds good to have a CronJob template.

**Comment by balboah** [comment] 2017-12-22 08:33
@hongchaodeng thanks for your answers, appreciated. The main reason why I asked `3` is that while testing, I got the error (don't remember the exact wording) "the cluster has failed, please delete CR and try again". Then I thought, why don't it just delete the CR itself when it already knows that it has failed and when it has backup settings

**Comment by balboah** [comment] 2018-01-03 14:39
Here is the exact log message which I triggered again when rolling all nodes to a new instance type: `level=warning msg="fail to handle event: ignore failed cluster (control-etcd). Please delete its CR" pkg=controller`

This is something I feel should be handled automatically

**Comment by alexandrem** [comment] 2018-01-03 19:16
That's something I wanted to bring up, thanks for the thread.

To my knowledge the backup/restore functionalities changed drastically after v0.5. Back then we had the auto continuous backups and automatic restore from the etcd-operator when cluster was unhealthy, e.g cluster split and quorum lost.

The main issue is that under network outage or severe cluster degradation, if quorum is lost for many minutes then etcd-operator will delete all member pods. Then, will declare cluster members as dead and ask to recreate the cluster resource.

It seems there's a lot of work involved for the human operators (or need for a better automatic system around).

I've simulated these kind of outages a lot lately. 

If members are gone and deleted by the etcd-operator, then restore works like this:

1. Need to create manually a restore resource from a healthy backup file path on S3.
2. Restored cluster cannot replace a previous cluster with same name. So that means we must use a different cluster name. Problem is this will break existing clients because they most likely use the existing K8s service name if they are pods on the same cluster.
3. Better approach is then to delete the existing EtcdCluster resource before. However, when quorum is lost the members were deleted by the etcd-operator and their pod resources will still hang around with a static name. So we must not only delete the EtcdCluster but also all the pod resources (e.g etcd-cluster-0000, etcd-cluster-0001, ...)

Should we expect to handle all these edge cases outside of etcd operator?

**Comment by hongchaodeng** [comment] 2018-01-03 19:27
> The main issue is that under network outage or severe cluster degradation, if quorum is lost for many minutes then etcd-operator will delete all member pods. 

Can you create a separate issue for this? It is orthogonal to the discussion here -- which is about more automated backup/restore operations here. But the issue you mentioned above is about some failure scenarios. Please write down more details of the failure scenarios. We would like to solve them, and I can think of some more appropriate ways to solve them.

**Comment by alexandrem** [comment] 2018-01-03 19:42
Yes certainly.

I was under the impression that this was the expected behavior, as is documented in this design doc about persistent volumes and disaster recovery (cases C & D):

https://github.com/coreos/etcd-operator/blob/master/doc/design/persistent_volumes_etcd_data.md

This document mentions the restore scenarios, but it's not clear if it should be automated by operator (I believe it initially was planned to).

I will create a new issue to discuss this topic.

**Comment by rjtsdl** [comment] 2018-01-05 22:30
@hongchaodeng 

Follow-up questions on backup. 

Currently S3 will provide a **path** to the actually S3 location. This would be a full path. Does that mean **only one** copy of snapshot will be backed up? 

Also

There are cases we would like to split the whole snapshot into blocks. So if it is a **folder**, rather than **path**, things would be much easier. Want to hear what is the way going forward.

**Comment by xiang90** [comment] 2018-01-05 22:38
@rjtsdl 

One CR per backup is the new logic. If you want to keep backups, then you create CRs with different paths. You can easily do that by setting up a cron job.

**Comment by xiang90** [comment] 2018-01-05 22:38
> There are cases we would like to split the whole snapshot into blocks.

the current operator has no support for this.

**Comment by rjtsdl** [comment] 2018-01-05 22:44
@xiang90 

> One CR per backup is the new logic. If you want to keep backups, then you create CRs with different paths. You can easily do that by setting up a cron job.

Great idea !

> the current operator has no support for this.

Good to know. I think, I just want to hear if any work planning in the future?

**Comment by xiang90** [comment] 2018-01-05 22:45
> There are cases we would like to split the whole snapshot into blocks.

this is a feature request. please create a new issue for it, and talk about why you want it. thanks.

**Comment by rjtsdl** [comment] 2018-01-05 22:47
@xiang90 

Sure, I will.

For the CronJob, do you have a sample? It doesn't need to be crafted perfect. Just want to play around.

**Comment by hongchaodeng** [comment] 2018-02-01 18:23
Closing this as questions were answered.
Other questions continue at https://github.com/coreos/etcd-operator/issues/1841, https://github.com/coreos/etcd-operator/issues/1832

**Closed by hongchaodeng** 2018-02-01 18:23 UTC
Labels: kind/question
