### ISSUE TITLE
Etcd-operator does not automatically migrate etcd instance pods from a node that’s down. 

### ISSUE THREAD

**Issue by georgekuruvillak** [coreos/etcd-operator#1839] opened 2018-01-09 09:14 UTC
Etcd-operator does not automatically migrate pods from a node that’s down. The resulting pod is set to UNREADY and the pod is provided with a deletionTimestamp
and deletionGracePeriodSeconds. This results in erroneous operation as we need the pods be migrated/recreated on an active node. It is also noted that the Phase of the pod remains as Running. Should we not add a probe too in addition to just checking the Phase to ensure Pod liveliness? 

## Steps to recreate the issue.

```
# kubectl get nodes
NAME         STATUS    ROLES     AGE       VERSION
master.k8s   Ready     master    1h        v1.8.4
node1.k8s    Ready     <none>    1h        v1.8.4
node2.k8s    Ready     <none>    1h        v1.8.4
```
```
# kubectl get nodes
NAME         STATUS    ROLES     AGE       VERSION
master.k8s   Ready     master    1h        v1.8.4
node1.k8s    Ready     <none>    1h        v1.8.4
node2.k8s    Ready     <none>    1h        v1.8.4
```
 
Now I bring down node1.k8s.
 
```
# kubectl get nodes
NAME         STATUS     ROLES     AGE       VERSION
master.k8s   Ready      master    1h        v1.8.4
node1.k8s    NotReady   <none>    1h        v1.8.4
node2.k8s    Ready      <none>    1h        v1.8.4
```
But
```
# kubectl get pods -n etcd-operator -o wide
NAME                             READY     STATUS    RESTARTS   AGE       IP          NODE
etcd-operator-6c54d65cdd-pfxbj   1/1       Running   0          1h        10.32.0.3   node2.k8s
example-etcd-cluster-0003        1/1       Unknown   0          46m       10.38.0.2   node1.k8s
```
```
# kubectl get svc -n etcd-operator
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
example-etcd-cluster          ClusterIP   None             <none>        2379/TCP,2380/TCP   1h
example-etcd-cluster-client   ClusterIP   10.101.151.195   <none>        2379/TCP            1h
```
```
# kubectl exec -it etcd-operator-6c54d65cdd-pfxbj -n etcd-operator – sh
/ # wget example-etcd-cluster:2380
Connecting to example-etcd-cluster:2380 (10.38.0.2:2380)
wget: can't connect to remote host (10.38.0.2): Host is unreachable
```
Saw these issues pertaining to the same:
[https://github.com/coreos/etcd-operator/issues/1281](https://github.com/coreos/etcd-operator/issues/1281)
[https://github.com/coreos/etcd-operator/issues/1279](https://github.com/coreos/etcd-operator/issues/1279)

**Comment by hongchaodeng** [comment] 2018-01-09 17:30
@georgekuruvillak

Thanks for reporting the issue in such a good format!

Can you provide all components' versions, etcd-operator logs? etcd CR via `kubectl get etcdcluster example-etcd-cluster -o yaml`?

> The resulting pod is set to UNREADY and the pod is provided with a deletionTimestamp
and deletionGracePeriodSeconds. 

It sounds to me this could be caused by node eviction. And it further seems to me like there are two pods (no anti-affinity set) on the node brought down. This is actually a disastrous case. etcd cluster could not be migrated if there is any disaster, but be restored from a backup.

**Comment by georgekuruvillak** [comment] 2018-01-12 08:49
@hongchaodeng 

I am sorry I was not able to delineate the issue better. The cluster I deployed is a single instance etcd cluster with backup scheduled to AWS S3. The K8S cluster has 2 nodes. I took down the kubelet of the node on with the etcd instance pod was deployed to simulate abrupt node failure.  The node status after the operation is shown below:
```
# kubectl get nodes
NAME                                          STATUS     ROLES     AGE       VERSION
ip-10-250-26-254.eu-west-1.compute.internal   NotReady   node      21h       v1.8.2
ip-10-250-30-179.eu-west-1.compute.internal   Ready      node      1d        v1.8.2
```

Now when I check upon the pods:
```
# kubectl get pods -n etcd-operator  -o wide
NAME                                            READY     STATUS    RESTARTS   AGE       IP            NODE
etcd-main-aws-0000                              1/1       Unknown   0          18h       100.96.5.10   ip-10-250-26-254.eu-west-1.compute.internal
etcd-main-aws-backup-sidecar-75c8db8669-vl4rp   1/1       Running   0          18h       100.96.4.52   ip-10-250-30-179.eu-west-1.compute.internal
etcd-main-aws-backup-sidecar-75c8db8669-w6zqh   1/1       Unknown   0          18h       100.96.5.9    ip-10-250-26-254.eu-west-1.compute.internal
etcd-operator-65bb899cdd-9l5n8                  1/1       Running   3          21h       100.96.4.36   ip-10-250-30-179.eu-west-1.compute.internal
```

Since the backup sidecar pod is deployed as part of a deployment, K8S reschedules the new pod (`etcd-main-aws-backup-sidecar-75c8db8669-vl4rp`) though the old one (`etcd-main-aws-backup-sidecar-75c8db8669-w6zqh`) is in Unknown state.

However, a new pod for etcd instance is not created and scheduled and the old pod (`etcd-main-aws-0000`) remains in Unknown state. 

I dug further into the issue. I checked the Status field of this pod (`etcd-main-aws-0000`). 
```
# kubectl get pods etcd-main-aws-0000 -n etcd-operator -o json | jq .status
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2018-01-11T13:21:56Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2018-01-11T13:22:15Z",
      "status": "False",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2018-01-11T13:21:56Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "docker://b12e7a3ce6cd59309f2c6da10ea19218b7a715bccb6d7a4da5d25bd3caf57731",
      "image": "quay.io/coreos/etcd:v3.2.6",
      "imageID": "docker-pullable://quay.io/coreos/etcd@sha256:adf7159fe9b81587247744dbfb66adc48afbbe59dc98237be32ef2d51f0d1c84",
      "lastState": {},
      "name": "etcd",
      "ready": true,
      "restartCount": 0,
      "state": {
        "running": {
          "startedAt": "2018-01-11T13:22:15Z"
        }
      }
    }
  ],
  "hostIP": "10.250.26.254",
  "message": "Node ip-10-250-26-254.eu-west-1.compute.internal which was running pod etcd-main-aws-0000 is unresponsive",
  "phase": "Running",
  "podIP": "100.96.5.10",
  "qosClass": "BestEffort",
  "reason": "NodeLost",
  "startTime": "2018-01-11T13:21:56Z"
}
```
I found that even though the Node is labeled as `NodeLost`, the etcd pod has `"phase": "Running"` and  
```
 "state": {
        "running": {
          "startedAt": "2018-01-11T13:22:15Z"
        }
  ...
  }
```
In the reconcile logic, we just check the Phase of the pod which is erroneously shown as `Running` by K8S control plane. I guess this is preventing a new etcd pod from being spawned to take over from the one in the failed node.

## etcd CR Info:
```
# kubectl get etcdclusters etcd-main-aws -n etcd-operator -o yaml
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"etcd.database.coreos.com/v1beta2","kind":"EtcdCluster","metadata":{"annotations":{},"name":"etcd-main-aws","namespace":"etcd-operator"},"spec":{"backup":{"backupIntervalInSecond":30,"maxBackups":5,"s3":{"awsSecret":"aws","s3Bucket":"example-etcd"},"storageType":"S3"},"pod":{"labels":{"role":"main-aws"},"pv":{"volumeSizeInMB":8000}},"size":1,"version":"3.2.6"}}
  clusterName: ""
  creationTimestamp: 2018-01-11T13:21:55Z
  generation: 0
  initializers: null
  name: etcd-main-aws
  namespace: etcd-operator
  resourceVersion: "343295"
  selfLink: /apis/etcd.database.coreos.com/v1beta2/namespaces/etcd-operator/etcdclusters/etcd-main-aws
  uid: 651f3031-f6d2-11e7-9dfa-5af8083a9685
spec:
  backup:
    autoDelete: false
    backupIntervalInSecond: 30
    maxBackups: 5
    s3:
      awsSecret: aws
      s3Bucket: example-etcd
    storageType: S3
  baseImage: quay.io/coreos/etcd
  pod:
    labels:
      role: main-aws
    pv:
      volumeSizeInMB: 8000
    resources: {}
  size: 1
  version: 3.2.6
status:
  backupServiceStatus:
    backupSize: 0.023
    backups: 1
  clientPort: 2379
  conditions:
  - lastTransitionTime: 2018-01-11T13:22:20Z
    lastUpdateTime: 2018-01-11T13:22:20Z
    reason: Cluster available
    status: "True"
    type: Available
  currentVersion: 3.2.6
  members:
    ready:
    - etcd-main-aws-0000
  phase: Running
  serviceName: etcd-main-aws-client
  size: 1
  targetVersion: ""
```
## K8S details:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-10-05T00:41:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
I have tweaked the operator slightly to create a PVC for the etcd pod and re-attach the same PVC for the new pod that is to come up in case the old one failed for some reason. So the logs will have some additional information pertaining to the same.

## etcd operator logs:
```
# kubectl logs etcd-operator-65bb899cdd-9l5n8 -n etcd-operator
time="2018-01-11T13:17:33Z" level=info msg="creating cluster with Spec:" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="{" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    "size": 1," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    "baseImage": "quay.io/coreos/etcd"," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    "version": "3.2.6"," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    "pod": {" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "labels": {" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="            "role": "main-aws"" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        }," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "resources": {}," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "pv": {" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="            "volumeSizeInMB": 8000" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        }" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    }," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    "backup": {" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "storageType": "S3"," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "s3": {" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="            "s3Bucket": "example-etcd"," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="            "awsSecret": "aws"" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        }," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "backupIntervalInSecond": 30," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "maxBackups": 5," cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="        "autoDelete": false" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="    }" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="}" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="backup sidecar deployment and service created" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="Volume to be added: etcd-main-aws-0000-pvc" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="cluster created with seed member (etcd-main-aws-0000)" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:33Z" level=info msg="start running..." cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:41Z" level=info msg="skip reconciliation: running ([]), pending ([etcd-main-aws-0000])" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:49Z" level=info msg="skip reconciliation: running ([]), pending ([etcd-main-aws-0000])" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:57Z" level=info msg="Start reconciling" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:17:57Z" level=info msg="Finish reconciling" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:18:05Z" level=info msg="Start reconciling" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:18:05Z" level=info msg="Finish reconciling" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:18:14Z" level=info msg="Start reconciling" cluster-name=etcd-main-aws pkg=cluster
time="2018-01-11T13:18:14Z" level=info msg="Finish reconciling" cluster-name=etcd-main-aws pkg=cluster
...
```
## Related K8S issues
* [one node down, but pods on the node status.phase still Running #48920](https://github.com/kubernetes/kubernetes/issues/48920)
* [If pod reason is "NodeLost", set the count of ready containers as 0. #45465](https://github.com/kubernetes/kubernetes/pull/45465)
* [daemonset: when node lost, the pod's "READY" is incorrect #45016](https://github.com/kubernetes/kubernetes/issues/45016)

**Comment by georgekuruvillak** [comment] 2018-01-12 09:53
If I tweaked the pollPods function to incorporate a probe to the etcd instance and then decide the real Running status, then the aforementioned issue is was identified to have got resolved. If this fix is sufficient, I can help with a pull request.

```
func (c *Cluster) pollPods() (running, unready, pending []*v1.Pod, err error) {
	podList, err := c.config.KubeCli.Core().Pods(c.cluster.Namespace).List(k8sutil.ClusterListOpt(c.cluster.Name))
	if err != nil {
		return nil, nil, nil, fmt.Errorf("failed to list running pods: %v", err)
	}

	for i := range podList.Items {
		pod := &podList.Items[i]
		if len(pod.OwnerReferences) < 1 {
			c.logger.Warningf("pollPods: ignore pod %v: no owner", pod.Name)
			continue
		}
		if pod.OwnerReferences[0].UID != c.cluster.UID {
			c.logger.Warningf("pollPods: ignore pod %v: owner (%v) is not %v",
				pod.Name, pod.OwnerReferences[0].UID, c.cluster.UID)
			continue
		}
		switch pod.Status.Phase {
		case v1.PodRunning:
			if c.getMemberStatus(pod) {
				running = append(running, pod)
			} else {
				unready = append(unready, pod)
			}
		case v1.PodPending:
			pending = append(pending, pod)
		}
	}

	return running, unready, pending, nil
}

func (c *Cluster) getMemberStatus(pod *v1.Pod) bool {
	sc := c.isSecureClient()
	m := &etcdutil.Member{Name: pod.Name, Namespace: pod.Namespace, SecureClient: sc}
	url := m.ClientURL()
	healthy, err := etcdutil.CheckHealth(url, c.tlsConfig)
	if err != nil {
		c.logger.Warningf("health check of etcd member (%s) failed: %v", url, err)
	}
	if healthy {
		return true
	}
	return false
}
```

**Comment by hongchaodeng** [comment] 2018-01-12 19:27
What version of etcd-operator?

> "version": "3.2.6"

Not recommend 3.2.6 . I would recommend 3.2.13+.

**Comment by hongchaodeng** [comment] 2018-01-12 21:26
From the above information,

> size": 1," 

It's one member cluster.

> etcd-main-aws-0000                              1/1       Unknown   0          18h       100.96.5.10   ip-10-250-26-254.eu-west-1.compute.internal

The member sits on node `ip-10-250-26-254.eu-west-1.compute.internal`.

> ip-10-250-26-254.eu-west-1.compute.internal   NotReady   node      21h       v1.8.2

And the node was shutdown and restarted.

Currently, etcd pod could not endure crash scenario like this.

**Comment by hongchaodeng** [comment] 2018-01-12 22:33
More detailed writeout and explanation on https://github.com/coreos/etcd-operator/issues/1856.

Would you mind if we close this and converge discussion there?

**Comment by georgekuruvillak** [comment] 2018-01-13 08:20
@hongchaodeng 

The controller manager is supposed to orchestrate the pod eviction after 5 minutes. Surprisingly, that has not happened. The age of `etcd-main-aws-0000` shows 18 hrs.
```
# kubectl get pods -n etcd-operator  -o wide
NAME                                            READY     STATUS    RESTARTS   AGE       IP            NODE
etcd-main-aws-0000                              1/1       Unknown   0          18h       100.96.5.10   ip-10-250-26-254.eu-west-1.compute.internal
etcd-main-aws-backup-sidecar-75c8db8669-vl4rp   1/1       Running   0          18h       100.96.4.52   ip-10-250-30-179.eu-west-1.compute.internal
etcd-main-aws-backup-sidecar-75c8db8669-w6zqh   1/1       Unknown   0          18h       100.96.5.9    ip-10-250-26-254.eu-west-1.compute.internal
etcd-operator-65bb899cdd-9l5n8                  1/1       Running   3          21h       100.96.4.36   ip-10-250-30-179.eu-west-1.compute.internal
```

Please do close this issue and take up further discussions at [#1856](https://github.com/coreos/etcd-operator/issues/1856)

**Comment by xiang90** [comment] 2018-01-15 19:42
@georgekuruvillak 

Probably it worths some investigation on why controller manager did not evict pods after the node became unhealthy for 18hrs. the default timeout is 5 minutes.

i am going to close this issue as you suggested. please follow up this on #1856. thanks!

**Closed by xiang90** 2018-01-15 19:42 UTC
