### ISSUE TITLE
Complete failure?

### ISSUE THREAD

**Issue by djMax** [coreos/etcd-operator#777] opened 2017-02-15 15:22 UTC
We had a cluster with 3 nodes and backup configured. We had some sort of catastrophic event (still unclear what). First, all 3 etcd pods went away and it made no attempt to restart them. Then the backup pod went away after some hours, and no attempt to recreate. The volumes are still there, is there any way to recover?

**Comment by xiang90** [comment] 2017-02-15 15:26
@djMax Yes. As long as the volume is still there, etcd-operator can recover it automatically. You can create a new cluster with restore policy set: https://github.com/coreos/etcd-operator/blob/master/pkg/spec/cluster.go#L93.

You need to fill in the original storage type and the cluster name.

Please try this first. There is a backup recovery plan too. But let's see if this works for you.

**Comment by xiang90** [comment] 2017-02-15 15:31
Also can you get the log of the etcd operator for us? We would like to investigate into the root cause.

**Comment by djMax** [comment] 2017-02-15 15:32
Me too. I think the operator pod was restarted at some point and I can't find logs from the time period. Now it just says:

```
time="2017-02-15T15:30:52Z" level=info msg="etcd-operator Version: 0.2.0"
time="2017-02-15T15:30:52Z" level=info msg="Git SHA: 0ed2c67"
time="2017-02-15T15:30:52Z" level=info msg="Go Version: go1.7.5"
time="2017-02-15T15:30:52Z" level=info msg="Go OS/Arch: linux/amd64"
time="2017-02-15T15:31:37Z" level=info msg="use in cluster client from k8s library"
time="2017-02-15T15:31:38Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-02-15T15:31:38Z" level=info msg="starts running from watch version: 13732244" pkg=controller
time="2017-02-15T15:31:38Z" level=info msg="start watching at 13732244" pkg=controller```

And there IS a valid cluster, but it doesn't seem to care.

**Comment by xiang90** [comment] 2017-02-15 15:34
@djMax Can you get the information of that cluster in yaml format via kubectl? (<Yourcluster> -o yaml)

**Comment by djMax** [comment] 2017-02-15 15:35
Sorry, I can't do the translation of that code to yaml yet. Is that just

```
apiVersion: "coreos.com/v1"
kind: "EtcdCluster"
metadata:
  name: "etcd-cluster"
spec:
  size: 3
  version: "3.1.0"
  restore: true
  backup:
    backupIntervalInSecond: 30
    maxBackups: 5
    volumeSizeInMB: 512
    storageType: "PersistentVolume"```

**Comment by djMax** [comment] 2017-02-15 15:36
```apiVersion: coreos.com/v1
data: eyJhcGlWZXJzaW9uIjoiY29yZW9zLmNvbS92MSIsImtpbmQiOiJFdGNkQ2x1c3RlciIsIm1ldGFkYXRhIjp7Im5hbWUiOiJldGNkLWNsdXN0ZXIifSwic3BlYyI6eyJiYWNrdXAiOnsiYmFja3VwSW50ZXJ2YWxJblNlY29uZCI6MzAsIm1heEJhY2t1cHMiOjUsInN0b3JhZ2VUeXBlIjoiUGVyc2lzdGVudFZvbHVtZSIsInZvbHVtZVNpemVJbk1CIjo1MTJ9LCJzaXplIjozLCJ2ZXJzaW9uIjoiMy4xLjAifX0=
kind: EtcdCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"extensions/v1beta1","metadata":{"name":"etcd-cluster","namespace":"default","creationTimestamp":null},"data":"eyJhcGlWZXJzaW9uIjoiY29yZW9zLmNvbS92MSIsImtpbmQiOiJFdGNkQ2x1c3RlciIsIm1ldGFkYXRhIjp7Im5hbWUiOiJldGNkLWNsdXN0ZXIifSwic3BlYyI6eyJiYWNrdXAiOnsiYmFja3VwSW50ZXJ2YWxJblNlY29uZCI6MzAsIm1heEJhY2t1cHMiOjUsInN0b3JhZ2VUeXBlIjoiUGVyc2lzdGVudFZvbHVtZSIsInZvbHVtZVNpemVJbk1CIjo1MTJ9LCJzaXplIjozLCJ2ZXJzaW9uIjoiMy4xLjAifX0="}'
  creationTimestamp: 2017-01-29T03:56:25Z
  name: etcd-cluster
  namespace: default
  resourceVersion: "13731990"
  selfLink: /apis/coreos.com/v1/namespaces/default/etcdclusters/etcd-cluster
  uid: e7702386-e5d6-11e6-b0e1-12b67614d9ae
spec:
  antiAffinity: false
  backup:
    backupIntervalInSecond: 30
    cleanupBackupsOnClusterDelete: false
    maxBackups: 5
    storageType: PersistentVolume
    volumeSizeInMB: 512
  size: 3
  version: v3.1.0-alpha.1
status:
  conditions:
  - reason: 'Current cluster size: 1, desired cluster size: 3'
    transitionTime: 2017-01-29T03:56:37.552695859Z
    type: ScalingUp
  - reason: 'Current cluster size: 1, desired cluster size: 3'
    transitionTime: 2017-01-29T03:56:50.577391783Z
    type: ScalingUp
  - reason: 'Current cluster size: 2, desired cluster size: 3'
    transitionTime: 2017-01-29T03:56:58.751829979Z
    type: ScalingUp
  - reason: 'Current cluster size: 2, desired cluster size: 3'
    transitionTime: 2017-01-29T03:57:06.769458412Z
    type: ScalingUp
  - reason: ""
    transitionTime: 2017-01-29T03:57:15.007193737Z
    type: Ready
  controlPaused: false
  currentVersion: v3.1.0-alpha.1
  phase: Running
  reason: ""
  size: 3
  targetVersion: ""```

**Comment by xiang90** [comment] 2017-02-15 15:42
@djMax OK. So here is what happened.

The etcd cluster is created in a alpha version of etcd operator. It uses EtcdCluster as its TPR kind.
You updated etcd-operator to 0.2.0. We updated the TPR kind, see https://github.com/coreos/etcd-operator/releases/tag/v0.2.0.

So the etcd operator does not pick up your old cluster.

**Comment by djMax** [comment] 2017-02-15 15:44
And to bring it over? Just change the type? How do I invoke the restore bit?

**Comment by djMax** [comment] 2017-02-15 15:44
Should I delete one of these, or is one missing?

```
k get thirdpartyresources                                                                                  1 ↵  998  10:44:26
NAME                      DESCRIPTION             VERSION(S)
cluster.etcd.coreos.com   Managed etcd clusters   v1beta1
etcd-cluster.coreos.com   Managed etcd clusters   v1
```

**Comment by xiang90** [comment] 2017-02-15 15:46
@djMax Do you still want to recover the cluster? Or it is OK for you to lose all the data?

If you can lose all your data, remove 

```
etcd-cluster.coreos.com   Managed etcd clusters   v1
```

create a new cluster under `cluster.etcd.coreos.com`. 

we will not break anything this significant again. (etcd operator is beta now)

**Comment by djMax** [comment] 2017-02-15 15:47
I want to recover not so much because of the data but just so I know what to do in the future... But if that's a long painful mess, then so be it. It does seem like I should remove that alwaysPull policy lest this happen again.

**Comment by xiang90** [comment] 2017-02-15 15:48
@djMax Yea... The operator deployment should probably pin to a specific release version. Maybe you can help to update the example deployment to pin to :0.0.2? Thank you!

**Comment by djMax** [comment] 2017-02-15 15:53
Like this? https://github.com/coreos/etcd-operator/pull/778

**Comment by djMax** [comment] 2017-02-15 16:06
```time="2017-02-15T15:54:31Z" level=info msg="etcd-operator Version: 0.2.0"                             ✓  2 ⚙  1068  11:06:05
time="2017-02-15T15:54:31Z" level=info msg="Git SHA: 0ed2c67"
time="2017-02-15T15:54:31Z" level=info msg="Go Version: go1.7.5"
time="2017-02-15T15:54:31Z" level=info msg="Go OS/Arch: linux/amd64"
time="2017-02-15T15:55:16Z" level=info msg="use in cluster client from k8s library"
time="2017-02-15T15:55:16Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-02-15T15:55:16Z" level=info msg="starts running from watch version: 13737005" pkg=controller
time="2017-02-15T15:55:16Z" level=info msg="start watching at 13737005" pkg=controller
time="2017-02-15T15:57:09Z" level=error msg="cluster failed to setup: invalid cluster spec: spec: backup and restore storage types are different" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:03:15Z" level=info msg="creating cluster with Spec (spec.ClusterSpec{Size:3, Version:\"3.1.0\", Paused:false, Pod:(*spec.PodPolicy)(nil), Backup:(*spec.BackupPolicy)(0xc420144f00), Restore:(*spec.RestorePolicy)(0xc420463340), SelfHosted:(*spec.SelfHostedPolicy)(nil)}), Status (spec.ClusterStatus{Phase:\"\", Reason:\"\", ControlPaused:false, Conditions:[]spec.ClusterCondition(nil), Size:0, CurrentVersion:\"\", TargetVersion:\"\"})" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:03:15Z" level=info msg="restoring cluster from existing backup (etcd-cluster)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:03:15Z" level=info msg="backup replica set and service created" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:03:24Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:03:54Z" level=error msg="check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:03:54Z" level=error msg="fail to do disaster recovery: check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:04:02Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:04:32Z" level=error msg="check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:04:32Z" level=error msg="fail to do disaster recovery: check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:04:40Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:05:10Z" level=error msg="check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:05:10Z" level=error msg="fail to do disaster recovery: check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:05:18Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:05:48Z" level=error msg="check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:05:48Z" level=error msg="fail to do disaster recovery: check backup (etcd-cluster-backup-sidecar:19999) failed: Head http://etcd-cluster-backup-sidecar:19999/v1/backup?etcdVersion=3.1.0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" cluster-name=etcd-cluster pkg=cluster
time="2017-02-15T16:05:56Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=etcd-cluster pkg=cluster```

**Comment by djMax** [comment] 2017-02-15 16:16
Now the pv and pvc are gone. So I guess I give up on recovery.

**Comment by hongchaodeng** [comment] 2017-02-15 16:35
@djMax

The only release version that understands previous TPR is `0.0.1` . You can try to pin your deployment image to that. But please do it local, not as https://github.com/coreos/etcd-operator/pull/778 .

We recently release beta version:
https://github.com/coreos/etcd-operator/releases/tag/v0.2.0
After this, the TPR api will be more stable and we will provide migration plan if needed.

**Comment by djMax** [comment] 2017-02-15 16:54
The point of that PR is that if you don't pin the image, or at least tag it, you will blow up someone's etcd cluster like mine. Right?

**Comment by hongchaodeng** [comment] 2017-02-15 17:00
@djMax

The deployment is just an example. If you run serious production cluster, you need to a release version of the image. Doing `imagePullPolicy: Never` has unexpected side effect after all.

**Comment by djMax** [comment] 2017-02-15 17:01
I'd suggest you need a pretty clear callout that that's a setting that should be changed "for realsies."

**Comment by hongchaodeng** [comment] 2017-02-15 17:06
That made sense. Feel free to put a comment on both deployment.yaml and
deployment-aws.yaml

**Comment by xiang90** [comment] 2017-02-15 17:25
@hongchaodeng let's use released tag on the example deployment. it would take us little effort to maintain it, but would help "careless" users :P.

**Comment by hongchaodeng** [comment] 2017-02-15 17:26
@djMax 
Regarding your cluster, as long as your PVC still exists, there is still methods to recover it. But requires some effort. Let me know if you are interested.

**Comment by xiang90** [comment] 2017-02-15 18:11
fixed by https://github.com/coreos/etcd-operator/pull/779

**Closed by xiang90** 2017-02-15 18:11 UTC
Labels: kind/question
