### ISSUE TITLE
e2e flake: restore_from_a_different_name_cluster 

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#658] opened 2017-01-18 16:31 UTC
```
FAIL: TestClusterRestore/restore_cluster_from_backup/restore_from_a_different_name_cluster 
... (after restore) ...
util.go:369: 2017-01-18 08:13:18.603091964 +0000 UTC waiting size (3), etcd pods: []
restore_test.go:126: failed to create 3 members etcd cluster: still failing after 24 retries
restore_test.go:121: fail to wait backup deleted: failed to wait storage (PersistentVolume) to be deleted: still failing after 5 retries
```

**Comment by hongchaodeng** [comment] 2017-01-18 18:20
Operator logs:
```
time="2017-01-18T08:09:32Z" level=info msg="restoring cluster from existing backup (test-etcd-2urg9)" cluster-name=test-etcd-g9vyc
...
time="2017-01-18T08:11:22Z" level=error msg="cluster failed to setup: failed to wait backup copy pod (test-etcd-g9vyc-copyvolume, phase: Pending) to succeed: still failing after 12 retries
```

**Comment by hongchaodeng** [comment] 2017-01-18 18:23
For a normal case, it could be really fast
```
time="2017-01-18T18:12:45Z" level=info msg="restoring cluster from existing backup (test-etcd-hcp3n)" cluster-name=test-etcd-76m5e pkg=cluster
...
time="2017-01-18T18:12:53Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=test-etcd-76m5e 
time="2017-01-18T18:12:53Z" level=info msg="cluster created with seed member (test-etcd-76m5e-0000)" cluster-name=test-etcd-76m5e
```

**Comment by hongchaodeng** [comment] 2017-01-23 19:53
Not seeing for a week.
Not critical flake.
Closing.

**Comment by xiang90** [comment] 2017-01-23 20:26
we should not close a flake just because we have not seen it for a while. We need to know the root cause.

**Comment by hongchaodeng** [comment] 2017-01-23 21:03
It's not critical and not etcd operator problem according to the logs.
The copy job's pod is created and keeps "Pending" for a long time.

**Comment by xiang90** [comment] 2017-01-26 03:47
OK. This seems like a storage attachment slowness issue from K8S. I agree. Closing.

**Closed by xiang90** 2017-01-26 03:47 UTC
Labels: kind/bug
