### ISSUE TITLE
Problem with etcd in hostNetwork

### ISSUE THREAD

**Issue by caseydavenport** [coreos/etcd-operator#115] opened 2016-09-15 17:02 UTC
Ran into this today while trying to test the changes from #112 

```
NAME                                READY     STATUS    RESTARTS   AGE
po/etcd-cluster-0000                0/1       Error     0          1m
```

```
2016-09-15 00:49:12.196100 I | etcdmain: etcd Version: 3.0.8
2016-09-15 00:49:12.196134 I | etcdmain: Git SHA: d40982f
2016-09-15 00:49:12.196174 I | etcdmain: Go Version: go1.6.3
2016-09-15 00:49:12.196204 I | etcdmain: Go OS/Arch: linux/amd64
2016-09-15 00:49:12.196232 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2016-09-15 00:49:12.196591 I | etcdmain: listening for peers on http://0.0.0.0:2380
2016-09-15 00:49:12.196725 I | etcdmain: listening for client requests on 0.0.0.0:2379
2016-09-15 00:49:12.213419 E | netutil: could not resolve host etcd-cluster-0000:2380
2016-09-15 00:49:12.236475 I | etcdmain: stopping listening for client requests on 0.0.0.0:2379
2016-09-15 00:49:12.236515 I | etcdmain: stopping listening for peers on http://0.0.0.0:2380
2016-09-15 00:49:12.236541 I | etcdmain: --initial-cluster must include etcd-cluster-0000=http://etcd-cluster-0000:2380 given --initial-advertise-peer-urls=http://etcd-cluster-0000:2380
```

Looks like it's failing to resolve etcd-cluster-0000.  I'll investigate.

**Comment by xiang90** [comment] 2016-11-16 22:19
Fixed by #366

**Closed by xiang90** 2016-11-16 22:19 UTC
Labels: kind/bug

**Comment by bamb00** [comment] 2017-05-18 23:12
Hi,

Is there a fix or workaround for the hostNetwork-true? I'm running  etcd 3.1.6.  What workaround I can apply from Kubernetes?

Thanks in Advance.

**Comment by hongchaodeng** [comment] 2017-05-18 23:13
@bamb00 
What's the context? What are you trying to do?

**Comment by bamb00** [comment] 2017-05-19 00:46
The issue is reference in @caseydavenport with the link from kubernetes (kubernetes/kubernetes#17406).  I'm just wondering is there a workaround for this issue.
