### ISSUE TITLE
There is no path to upgrade backup sidecar to a new version

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd-operator#1466] opened 2017-10-02 15:28 UTC
Sidecar gets deployed as part of the EtcdCluster. While upgrading etcd-operator from v0.5.2 to 0.6.0 I noticed that there is no path to upgrade the sidecar as its version was still showing v0.5.2

**Comment by hongchaodeng** [comment] 2017-10-02 18:34
Upgrading operator will automatically upgrade backup sidecar as well.
They should be the same version.

**Comment by raoofm** [comment] 2017-10-02 19:57
It didnt upgrade the sidecar, if you want i can test again.

**Comment by fanminshi** [comment] 2017-10-02 20:11
@raoofm can you show me the exact steps of your upgrade process.
I upgraded etcd-operator from v0.5.2 to v0.6.0 and saw the sidecar also updated its version to v0.6.0.

**Comment by hongchaodeng** [comment] 2017-10-19 20:56
Closing since unreproducible.
Feel free to reopen if you still have any issues/questions.

**Closed by hongchaodeng** 2017-10-19 20:56 UTC
