### ISSUE TITLE
when I using the deploy the operator, it start failed ?

### ISSUE THREAD

**Issue by yan234280533** [coreos/etcd-operator#1293] opened 2017-07-14 07:51 UTC
when I using the deploy the operator, it start failed ?

E0714 07:41:09.905723       5 election.go:226] error retrieving resource lock default/etcd-operator: Get https://10.96.0.1:443/api/v1/namespaces/default/endpoints/etcd-operator: dial tcp 10.96.0.1:443: i/o timeout

the version I used:
k8s:  v1.7.0"

and I was done the step of rbac in this url:

https://github.com/coreos/etcd-operator/blob/master/doc/user/rbac.md

**Comment by wilhelmguo** [comment] 2017-07-14 09:36
It seems that the operator pod can't connect to you apiserver. Check your apiserver and network.

**Comment by yan234280533** [comment] 2017-07-14 09:39
I test in node telnet 10.96.0.1 443 ,it telnet succeed.

**Comment by wilhelmguo** [comment] 2017-07-14 09:41
You should test in one pod of the node telnet 10.96.0.1 443 ,check if success?

**Comment by yan234280533** [comment] 2017-07-14 09:52
I redeploy it ,and deploy it in the master node.

it show the error log : 

etrieving resource lock default/etcd-operator: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default". (get endpoints etcd-operator)

**Comment by yan234280533** [comment] 2017-07-14 09:53
Can I deploy the  operator in default namespace? Or ,should I must deploy it in an new namespace?

**Comment by yan234280533** [comment] 2017-07-14 10:00
I deploy it in an new namespaces tst2, but it error:

time="2017-07-14T09:59:07Z" level=error msg="initialization failed: fail to create TPR: User "system:serviceaccount:tst2:default" cannot create thirdpartyresources.extensions at the cluster scope. (post thirdpartyresources.extensions)" pkg=controller

**Comment by yan234280533** [comment] 2017-07-14 10:01
root@VM-133-17-ubuntu:/data/etcd-operator/example# kubectl logs etcd-operator-3317057186-fww0g -n=tst2
time="2017-07-14T09:58:07Z" level=info msg="etcd-operator Version: 0.4.2" 
time="2017-07-14T09:58:07Z" level=info msg="Git SHA: cbb8715" 
time="2017-07-14T09:58:07Z" level=info msg="Go Version: go1.8.1" 
time="2017-07-14T09:58:07Z" level=info msg="Go OS/Arch: linux/amd64" 
time="2017-07-14T09:58:37Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"tst2", Name:"etcd-operator", UID:"0165f84a-687b-11e7-b140-525400c1c607", APIVersion:"v1", ResourceVersion:"32024", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' etcd-operator-3317057186-fww0g became leader" 
E0714 09:58:37.185477       7 event.go:199] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-operator.14d129fced7144b9", GenerateName:"", Namespace:"tst2", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Endpoints", Namespace:"tst2", Name:"etcd-operator", UID:"0165f84a-687b-11e7-b140-525400c1c607", APIVersion:"v1", ResourceVersion:"32024", FieldPath:""}, Reason:"LeaderElection", Message:"etcd-operator-3317057186-fww0g became leader", Source:v1.EventSource{Component:"etcd-operator-3317057186-fww0g", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{sec:63635623117, nsec:183206585, loc:(*time.Location)(0x21c9720)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63635623117, nsec:183206585, loc:(*time.Location)(0x21c9720)}}, Count:1, Type:"Normal"}': 'User "system:serviceaccount:tst2:default" cannot create events in the namespace "tst2". (post events)' (will not retry!)
time="2017-07-14T09:58:37Z" level=error msg="initialization failed: fail to create TPR: User "system:serviceaccount:tst2:default" cannot create thirdpartyresources.extensions at the cluster scope. (post thirdpartyresources.extensions)" pkg=controller 
time="2017-07-14T09:58:37Z" level=info msg="retry in 30s..." pkg=controller 
time="2017-07-14T09:59:07Z" level=error msg="initialization failed: fail to create TPR: User "system:serviceaccount:tst2:default" cannot create thirdpartyresources.extensions at the cluster scope. (post thirdpartyresources.extensions)" pkg=controller 
time="2017-07-14T09:59:07Z" level=info msg="retry in 30s..." pkg=controller 
time="2017-07-14T09:59:37Z" level=error msg="initialization failed: fail to create TPR: User "system:serviceaccount:tst2:default" cannot create thirdpartyresources.extensions at the cluster scope. (post thirdpartyresources.extensions)" pkg=controller 
time="2017-07-14T09:59:37Z" level=info msg="retry in 30s..." pkg=controller 
time="2017-07-14T10:00:07Z" level=error msg="initialization failed: fail to create TPR: User "system:serviceaccount:tst2:default" cannot create thirdpartyresources.extensions at the cluster scope. (post thirdpartyresources.extensions)" pkg=controller 
time="2017-07-14T10:00:07Z" level=info msg="retry in 30s..." pkg=controller 
time="2017-07-14T10:00:37Z" level=error msg="initialization failed: fail to create TPR: User "system:serviceaccount:tst2:default" cannot create thirdpartyresources.extensions at the cluster scope. (post thirdpartyresources.extensions)" pkg=controller 
time="2017-07-14T10:00:37Z" level=info msg="retry in 30s..." pkg=controller

**Comment by hongchaodeng** [comment] 2017-07-14 17:41
It seems like you don't have perm. Did you set up RBAC right?

**Comment by zhangax** [comment] 2017-08-16 02:26
I am also found this problem.My issue is about use helm deploy etcd-operator,but the logs tell me this:
E0816 02:24:43.328801       1 election.go:226] error retrieving resource lock default/etcd-operator: Get https://10.96.0.1:443/api/v1/namespaces/default/endpoints/etcd-operator: dial tcp 10.96.0.1:443: i/o timeout

I tried so many ways ,unluckly  don't fix it.

Any one could help me?

**Comment by yan234280533** [comment] 2017-08-16 09:13
@zhangax  I fixed it ,by using tcpdump to  capture the packages. Then we find it the problem of network.

**Comment by xiang90** [comment] 2017-08-16 16:16
@yan234280533 Great. I am closing this since it it not an etcd operator issue.

**Closed by xiang90** 2017-08-16 16:16 UTC

**Comment by zhangax** [comment] 2017-08-17 02:30
Do you mean enter the container？

**Comment by ggordan** [comment] 2017-10-23 09:06
Are you able to clarify what the issue was, how it was resolved in a little more detail? I've encountered the same problem and spent the better part of a day trying to figure out the cause. The following day it seems to have resolved itself. The other pods had no trouble talking to the apiserver including other pods on the same node.

etcd-operator version: v0.3.0
k8s version: 1.7

**Comment by iiwawe** [comment] 2017-11-17 02:22
@yan234280533 
你好，我也遇到了相同的问题，能具体说一下怎么解决的吗，多谢了。

**Comment by iiwawe** [comment] 2017-11-17 02:45
@yan234280533 
I got the same error:
error retrieving resource lock default/etcd-operator: Get https://10.96.0.1:443/api/v1/namespaces/default/endpoints/etcd-operator: dial tcp 10.96.0.1:443: i/o timeout
Can you show some detail how to solve it.

**Comment by ArcticSnowman** [comment] 2017-12-12 17:48
Getting a similar error:
` error retrieving resource lock default/etcd-operator: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default".`    This issue seems common and needs to be addressed in the documentation some where.
