### ISSUE TITLE
Disaster recovery from S3 fails when multiple backups with same timestamp

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/etcd-operator#1359] opened 2017-08-12 06:00 UTC
I copied our S3 backups folder from:
`${BUCKET_NAME}/v1/${CLUSTER_NAME}/` to 
`${BUCKET_NAME}/v1/${NAMESPACE}/${CLUSTER_NAME}/`
to enable restore from newer version of etcd-operator.

This caused all the backups S3 objects to have the same `Last Modified` timestamp, and until I deleted all but one of them, DR was cycling through seed pods over and over.

Here are etcd-operator logs from immediatly after `kubectl apply`ing the `etcdCluster` object:

```bash
time="2017-08-12T05:35:51Z" level=info msg="restoring cluster from existing backup (obfuscated)" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:35:51Z" level=info msg="backup sidecar deployment and service created" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:35:51Z" level=info msg="start running..." cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:35:56Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller
time="2017-08-12T05:35:59Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:35:59Z" level=info msg="cluster created with seed member (obfuscated-0000)" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:01Z" level=info msg="start watching at 471017" pkg=controller
time="2017-08-12T05:36:07Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0000])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:15Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0000])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:23Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0000])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:31Z" level=warning msg="all etcd pods are dead. Trying to recover from a previous backup" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:31Z" level=info msg="cluster created with seed member (obfuscated-0001)" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:39Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:47Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:36:55Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:03Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:11Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:19Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:27Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:35Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:43Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:51Z" level=info msg="skip reconciliation: running ([]), pending ([obfuscated-0001])" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:56Z" level=info msg="apiserver closed watch stream, retrying after 5s..." pkg=controller
time="2017-08-12T05:37:59Z" level=info msg="Start reconciling" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:59Z" level=info msg="running members: obfuscated-0001" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:37:59Z" level=info msg="cluster membership: obfuscated-0001" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:01Z" level=info msg="start watching at 471017" pkg=controller
time="2017-08-12T05:38:04Z" level=info msg="Finish reconciling" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:04Z" level=error msg="failed to reconcile: fail to add new member (obfuscated-0002): context deadline exceeded" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:17Z" level=error msg="failed to update members: context deadline exceeded" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:30Z" level=error msg="failed to update members: context deadline exceeded" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:39Z" level=info msg="Start reconciling" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:39Z" level=info msg="running members: obfuscated-0001" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:39Z" level=info msg="cluster membership: obfuscated-0002,obfuscated-0001" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:39Z" level=info msg="Disaster recovery" cluster-name=obfuscated pkg=cluster
time="2017-08-12T05:38:39Z" level=info msg="pods are still running (obfuscated-0001). Will try to make a latest backup from one of them." cluster-name=obfuscated pkg=cluster
```
The moment in the AWS console I deleted all but one of the backups, it started working and properly recovered the backup.

**Comment by hongchaodeng** [comment] 2017-09-11 20:32
@snarlysodboxer 
Can you provide more details about how to reproduce it?

> I copied our S3 backups folder from:
${BUCKET_NAME}/v1/${CLUSTER_NAME}/ to
${BUCKET_NAME}/v1/${NAMESPACE}/${CLUSTER_NAME}/
to enable restore from newer version of etcd-operator.

Also copying data in S3 bucket like this is somehow unexpected.

**Comment by hongchaodeng** [comment] 2017-09-17 17:03
I'm closing since it is going through some invalid path.

@snarlysodboxer Feel free to reopen if you have further questions.

**Closed by hongchaodeng** 2017-09-17 17:03 UTC
